### ISSUE TITLE
Delete from Redis after subscribing to the message

### ISSUE THREAD

**Issue by davidop** [Oriflame/RedisMessaging.ReliableDelivery#18]
Great contribution, I had been looking for something like that for some time. Is there a mechanism that eliminates the message from Redis once the subscription has picked it up?

**Comment by footcha** [comment]
Hi @davidop,
you can set up message TTL (time to live) - parameter `messageExpiration` in `subscriber.Reliably().Publish()`. When this period expires then a message is considered expired in Redis and is potentially removed from Redis by internal [Redis expiration process](https://redis.io/commands/expire).
Hence, a message is not removed from Redis right after it is successfully delivered but it remains in Redis for a user-defined period.

**Comment by davidop** [comment]
No choice? The interesting thing is that after receiving the published information it will be automatically deleted.

**Comment by footcha** [comment]
That is interesting. Default message TTL is 10 minutes. It should stay in Redis this period since a publish moment. `ReliableDelivery` does not delete a message.

**Comment by davidop** [comment]
Ok, thanks.
