### ISSUE TITLE
Pub / Sub Delays

### ISSUE THREAD

**Issue by davidop** [Oriflame/RedisMessaging.ReliableDelivery#19]
I have seen that if I publish a lot of data (10,000 users) concurrently, delays appear between the publication and the subscription. Can you think of any ideas to avoid these delays?

**Comment by footcha** [comment]
Hello @davidop, can you clarify mor precisely your publish rate? I.e. how many messages per second you publish?
The library as such should not add any delays to publishing messages because it uses built-in pub/sub feature in Redis.
Can you compare delays in pub/sub messaging without `ReliableDelivery` in place?

**Comment by davidop** [comment]
I publish 10,000 messages every 5 seconds. Right now I am doing load tests with the implementation of your library. Have you ever encountered similar problems? It is probably Redis configuration problem, but I would appreciate your help.

**Comment by footcha** [comment]
Well, such a workload can be an issue for Redis itself. It depends on many things but main contributors to messages delivery delay usually are network latency/bandwidth and message size. If average message is large (e.g. 10kB) then even Redis can be shortly overhelmed with processing messages.
I suggest to design a load test with messages containg up to 100B on less. In such a case there will be much more optimal aggregation of Redis messages into TCP packets (Redis pipelining will take significant effect here) and also Redis server will process smaller byte streams. With this test configuration you will get a picture of physical limitations in the overall infrastructure.

**Comment by footcha** [comment]
Hello @davidop,
did you manage to investigate the workload? Is this issue still valid or Can I closed it?
Thank you!

**Comment by davidop** [comment]
You can delete it.  I changed the focus of my development.  Thank you anyway
